### ISSUE TITLE
broken pkgconfig .pc files when USE_RELATIVE_PATHS=ON

### ISSUE THREAD

**Issue by rdieter** [psi-im/jdns#6]
if  USE_RELATIVE_PATHS=ON , then generated jdns.pc an qjdns.pc contain incorrect entries:

libdir=lib64
includedir=include/jdns

so, these end up wrong too:

Libs: -L${libdir} ...
Cflags: -I${includedir}

**Comment by drizt** [comment]
Will fix. Thanks!
