### ISSUE TITLE
QJDNS does not work with Qt 5.5 due to Qt bug

### ISSUE THREAD

**Issue by machinekoder** [psi-im/jdns#7]
This is not an issue of JDNS itself. I tested QJDNS with the newest Qt release 5.5 and run into a problems. Turns out to be a Qt bug https://bugreports.qt.io/browse/QTBUG-47011

Just want to inform developers trying to use QJDNS with Qt 5.5 and Linux that this will not work until the bug is fixed.

**Comment by drizt** [comment]
Thanks!

**Comment by strahlex** [comment]
Fixed in Qt 5.6.

**Comment by Neustradamus** [comment]
With an update of Qt to 5.6+ it is good?
Need to update the Qt min version?

**Comment by drizt** [comment]
Don't need.
